### ISSUE TITLE
some comments

### ISSUE THREAD

**Issue by joticajulian** [koindx/v2-core#2]
https://github.com/koindx/v2-core/blob/4e2661e1c0fb0eeba72653e360936a18b4f64983/assembly/Core.ts#L34
you can use `const configs = new core.config_object(args.token_a, args.token_b)` in this way you reduce mana consumption (there is no need to read the storage which is empty)

https://github.com/koindx/v2-core/blob/4e2661e1c0fb0eeba72653e360936a18b4f64983/assembly/Core.ts#L66
If I remember correctly, the `Token` contract from the sdk throws an error when the balance is zero. Check this I'm not sure. I prefer to use the `IToken.ts` interface that is created when compiling a token contract.

https://github.com/koindx/v2-core/blob/4e2661e1c0fb0eeba72653e360936a18b4f64983/assembly/Core.ts#L82
this is new for me. could you explain why the contract needs a minimum liquidity?

**Comment by vonlooten** [comment]
@ederaleng can I close this issue? Afaik you have improved the contracts already thanks to Julian's suggestions.

**Comment by ederaleng** [comment]
> @ederaleng can I close this issue? Afaik you have improved the contracts already thanks to Julian's suggestions.

Yes, the necessary improvements were applied to the contract
